--[피평가자/평가자 관리] user 삭제시 고려해야 하는 table 
DELETE FROM EVU_MNG WHERE EVU_EMP_NO = '3060';
DELETE FROM EVU_EMP WHERE EVU_EMP_NO = '3060';
DELETE FROM EVU_TASK WHERE EVU_EMP_NO = '3060';
DELETE FROM EVU_COMP WHERE EVU_EMP_NO = '3060';
DELETE FROM EVU_TOT WHERE EVU_EMP_NO = '3060';
DELETE FROM EVU_FILE WHERE EVU_STD_ID='202301' AND EMP_ID = (SELECT EVU_EMP_ID FROM EVU_EMP WHERE EVU_EMP_NO='3060');


-- 역량 평가 관리 -> 역량 평가 항목 설정  
77. SELECT ISNULL(COUNT(*),0) FROM EVU_CDP WHERE CDP_CD = 'COM0001' AND POST_CD = 'NN'

77. INSERT INTO EVU_CDP ( EVU_STD_ID, CDP_CD, CDP_NM, CDP_TYPE, CDP_MISSION, INS_USER_ID, INS_YMDHMS, POST_CD )
		VALUES ( '202301', 'COM0001', 'common역량', 'C', 'TDS가 아닌 공통 기본 역량 ', '00812', getdate() , 'NN' )

77. SELECT MAX(EVU_CDP_COMP_ID) FROM EVU_CDP_COMP WHERE EVU_STD_ID = '202301'

77. INSERT INTO EVU_CDP_COMP ( EVU_CDP_COMP_ID, EVU_STD_ID, EVU_CDP_CD, CATE_CD1, CATE_CD2, 
		CATE_CD3, ACT_DESC, DP_ORDER, INS_USER_ID, INS_YMDHMS, POST_CD, SCORE)
		VALUES ( 'COM20230100000000001', '202301', 'COM0001', 'C020000', 'C010000', 'C020201', '직무 행동 역량', '1',
		 '00812', getdate(), 'NN', '50' )

77. SELECT MAX(EVU_CDP_COMP_ID) FROM EVU_CDP_COMP WHERE EVU_STD_ID = '202301'

77. SELECT MAX(EVU_CDP_COMP_ID) FROM EVU_CDP_COMP WHERE EVU_STD_ID = '202301'

77. INSERT INTO EVU_CDP_COMP ( EVU_CDP_COMP_ID, EVU_STD_ID, EVU_CDP_CD, CATE_CD1, CATE_CD2, 
		CATE_CD3, ACT_DESC, DP_ORDER, INS_USER_ID, INS_YMDHMS, POST_CD, SCORE)
		VALUES ( 'COM20230100000000002', '202301', 'COM0001', 'C030000', 'C020200', 'C020102', '지식/스킬 역량', '2',
		 '00812', getdate(), 'NN', '25' )

77. SELECT MAX(EVU_CDP_COMP_ID) FROM EVU_CDP_COMP WHERE EVU_STD_ID = '202301'

77. SELECT MAX(EVU_CDP_COMP_ID) FROM EVU_CDP_COMP WHERE EVU_STD_ID = '202301'

77. INSERT INTO EVU_CDP_COMP ( EVU_CDP_COMP_ID, EVU_STD_ID, EVU_CDP_CD, CATE_CD1, CATE_CD2, 
		CATE_CD3, ACT_DESC, DP_ORDER, INS_USER_ID, INS_YMDHMS, POST_CD, SCORE)
		VALUES ( 'COM20230100000000003', '202301', 'COM0001', 'C010000', 'C010200', 'C010201', '공통적인 value', '3',
		 '00812', getdate(), 'NN', '25' )

77. SELECT EVU_STD_ID, EVU_STD_NM, EVU_YY FROM EVU_STD WHERE OPEN_YN = 'Y' ORDER BY EVU_YY DESC, EVU_STD_ID DESC

77. SELECT TOP 1 EVU_STD_ID FROM [EVU_STD]  ORDER BY EVU_YY DESC, EVU_STD_ID DESC

77. SELECT COUNT(C.EVU_CDP_SEQ)
		FROM EVU_CDP C INNER JOIN EVU_STD S ON (C.EVU_STD_ID = S.EVU_STD_ID)
		WHERE C.EVU_STD_ID = '202301'

77. SELECT C.EVU_CDP_SEQ, C.EVU_STD_ID, S.EVU_STD_NM, C.CDP_CD, C.CDP_NM, C.CDP_TYPE, C.CDP_MISSION, C.POST_CD, 
			CASE WHEN C.POST_CD = 'NN' THEN '공통' ELSE C.POST_CD END POST_NM,
			ROW_NUMBER() OVER( ORDER BY CDP_CD ASC ) AS CAPA_INDEX
		FROM EVU_CDP C INNER JOIN EVU_STD S ON (C.EVU_STD_ID = S.EVU_STD_ID)
		WHERE C.EVU_STD_ID = '202301'
		ORDER BY CDP_CD ASC
			OFFSET ( 1 - 1 ) ROWS 
			FETCH NEXT 20 ROWS ONLY

77. SELECT EVU_STD_ID, EVU_STD_NM, EVU_YY FROM EVU_STD WHERE OPEN_YN = 'Y' ORDER BY EVU_YY DESC, EVU_STD_ID DESC

77. SELECT * FROM EVU_CDP WHERE EVU_STD_ID = '202301' AND CDP_CD = 'COM0001' AND POST_CD = 'NN'

77. SELECT * FROM EVU_CDP_COMP WHERE EVU_STD_ID = '202301' AND EVU_CDP_CD = 'COM0001' AND POST_CD = 'NN'

--- 역량 평가 관리 -> TDS 역량 평가 설정 

97. SELECT EVU_STD_ID, EVU_STD_NM, EVU_YY FROM EVU_STD WHERE OPEN_YN = 'Y' ORDER BY EVU_YY DESC, EVU_STD_ID DESC

97. SELECT TOP 1 EVU_STD_ID FROM [EVU_STD]  ORDER BY EVU_YY DESC, EVU_STD_ID DESC

97. SELECT COUNT(*)
		FROM EVU_COMP_CATE
		WHERE VISIBLE = 'Y'
		AND CATE_CD LIKE CONCAT('C05','%')
		AND DEPTH = 2

97. SELECT *
		FROM EVU_COMP_CATE
		WHERE VISIBLE = 'Y'
		AND CATE_CD LIKE CONCAT('C05','%')
		AND DEPTH = 2

97. SELECT COUNT(*)
		FROM EVU_COMP_DEFINE D LEFT JOIN EVU_COMP_CATE CATE1 ON (D.CATE_CD1 = CATE1.CATE_CD)
			LEFT JOIN EVU_COMP_CATE CATE2 ON (D.CATE_CD2 = CATE2.CATE_CD)
			LEFT JOIN EVU_COMP_CATE CATE3 ON (D.CATE_CD3 = CATE3.CATE_CD)
		WHERE D.VISIBLE = 'Y'
		AND D.CATE_CD1='C060000'

97. SELECT CATE1.CATE_NM CATE_NM1,
			CATE2.CATE_NM CATE_NM2,
			CATE2.CATE_CD CATE_CD2,
			CATE3.CATE_NM CATE_NM3,
			CATE3.CATE_CD CATE_CD3,
			D.DEFINE_CD,
			D.COMP_TITLE,
			D.COMP_DEFINE,
			D.EVU_COMP_DEFINE_SEQ,
			D.PRIORITY,
			D.CUSTOM_YN,
			ISNULL(D2.CATE_CNT, 0) CATE_CNT
		FROM EVU_COMP_DEFINE D LEFT JOIN EVU_COMP_CATE CATE1 ON (D.CATE_CD1 = CATE1.CATE_CD)
			LEFT JOIN EVU_COMP_CATE CATE2 ON (D.CATE_CD2 = CATE2.CATE_CD)
			LEFT JOIN EVU_COMP_CATE CATE3 ON (D.CATE_CD3 = CATE3.CATE_CD)
			LEFT JOIN (SELECT CATE_CD2, COUNT(*) CATE_CNT 
					FROM EVU_COMP_DEFINE S 
					WHERE S.CATE_CD1='C060000'

					GROUP BY CATE_CD2) D2 ON (D2.CATE_CD2=D.CATE_CD2)
		WHERE D.VISIBLE = 'Y'
		AND D.CATE_CD1 = 'C060000'
		ORDER BY D.CATE_CD2 ASC, D.DEFINE_CD ASC, D.DP_ORDER ASC




