
--  평가 년도 리스트 
SELECT * 
		FROM EVU_STD
		WHERE OPEN_YN ='Y'
		ORDER BY  EVU_YY DESC, EVU_STD_ID DESC;

--  평가 스텝 리스트 
SELECT 
	D.EVU_STD_ID, 
	D.EVU_STD_NM, 
	D.EVU_YY, 
	S.EVU_STEP_CD, 
	S.EVU_STEP_NM, 
	S.EVU_SDATE, 
	S.EVU_EDATE, 
	S.ORDER_NO, 
	S.ETC_EVU_YN, 
	S.EVU_OPEN_YN
FROM EVU_STEP S 
INNER JOIN EVU_STD D ON (S.EVU_STD_ID = D.EVU_STD_ID)
WHERE S.EVU_STD_ID = '202001';

-- 평가 단계 설정 
select * 
from EVU_STEP es;
-- 평가 년도 기준 설정 
select *
from EVU_STD es;

--- 년도 별 평가 단계 
select count(*) as test
from  evu_step b 
inner join evu_std a on (a.EVU_STD_ID = b.EVU_STD_ID);

/*selectEvuTypeCheck*/
-- 메인 평가 타입 체크 
		SELECT
			CASE WHEN empCount > 0 THEN 1 ELSE 0 END isEmp,
			CASE WHEN (mngCount + taskCount) > 0 THEN 1 ELSE 0 END isMng
		FROM (
			SELECT
				COUNT(*) empCount,
				(SELECT COUNT(*) mngCount 
					FROM EVU_EMP E2 INNER JOIN EVU_MNG M ON (E2.EVU_EMP_NO=M.EVU_EMP_NO)
					WHERE E2.EVU_STD_ID='202201' AND m.EVU_MNG_ID = '00812') AS mngCount,
				(SELECT COUNT(*) taskCount 
					FROM EVU_EMP E2 INNER JOIN EVU_TASK T ON (E2.EVU_EMP_NO=T.EVU_EMP_NO)
					WHERE E2.EVU_STD_ID='202201' AND TASK_MNG_ID='00812') AS taskCount
			FROM EVU_EMP
			WHERE EVU_STD_ID='202201'
			AND EVU_EMP_ID='00812'
		) R

-- 피평가자 나의 진행 현황 
		/*selectEvuEmp*/
		SELECT EP.EVU_STD_ID, EP.EVU_EMP_NO, EP.CHASU, EP.EVU_STAT_CD, EP.EVU2_YN ,  EM.EVU_MNG_ID, EP.EVU_EMP_ID , EP.CUR_STEP_CD,
			U.BAND_CD, U.POST_CD, U.EMP_NM, U.EMP_TYPE, U.JOB_NM
		FROM EVU_EMP EP LEFT JOIN [USER] U ON (EP.EVU_EMP_ID = U.EMP_ID)
			LEFT JOIN EVU_MNG EM ON (EP.EVU_EMP_NO = EM.EVU_EMP_NO AND EM.CHASU = 1 AND EP.EVU_EMP_ID = '00812' AND EP.EVU_STD_ID = '202201')
		WHERE EP.EVU_EMP_ID = '00812' AND EP.EVU_STD_ID = '202201'

-- 평가자 현재 스텝 
/*selectMngCurEvuStep*/
SELECT TOP 1 EVU_STEP_CD
FROM EVU_STEP ST 
INNER JOIN EVU_STD S ON (ST.EVU_STD_ID = S.EVU_STD_ID) 
WHERE S.EVU_STD_ID = '202201'
AND CONVERT(CHAR(10), GETDATE(), 23) BETWEEN EVU_SDATE AND EVU_EDATE

select 
	es.END_YMD as t1,
	CONVERT(CHAR(10),es.END_YMD , 23) as t2,
	CONVERT(CHAR(10), GETDATE(), 23) as t3
from EVU_STD es;


11. /*evuStepDetail*/
		SELECT 
			D.EVU_STD_ID, D.EVU_STD_NM, D.EVU_YY,
			S.EVU_STEP_CD, S.EVU_STEP_NM, S.EVU_SDATE, S.EVU_EDATE, S.ORDER_NO, S.ETC_EVU_YN, S.EVU_OPEN_YN, S.ASSE_OPEN_YN,
			S.ORG_FILE_NAME, S.COMP_ITEM_YN, S.COMP_FEEDBACK_YN, S.COMP_RESULT_YN, S.COMP_TOT_YN
		FROM EVU_STEP S INNER JOIN EVU_STD D ON (S.EVU_STD_ID = D.EVU_STD_ID)
		WHERE S.EVU_STEP_CD = 'D1'
		AND S.EVU_STD_ID = '202201'

11. /* selectEvuEmpUserList */
		WITH CHA AS ( SELECT 1 AS CHASU UNION ALL SELECT CHASU + 1 FROM CHA WHERE CHASU <= 2 ) 
		SELECT 
			C.CHASU,T.EVU_MNG_SEQ, T.EMP_NM, T.EMP_ID, T.DUTY_CD, T.DUTY_NM, T.JOB_NM,  T.TASK_NM,
			ORG_ID,ORG_NM
		FROM CHA  C LEFT JOIN (
			SELECT 
				EM.EVU_MNG_SEQ AS EVU_MNG_SEQ, EM.CHASU,U.EMP_NM, U.EMP_ID, U.DUTY_CD, U.DUTY_NM, U.JOB_NM, 'T' AS TASK_NM, ORG_ID,ORG_NM
			FROM EVU_MNG EM LEFT JOIN EVU_EMP EE ON EM.EVU_EMP_NO = EE.EVU_EMP_NO
					LEFT JOIN [USER] U ON EVU_MNG_ID =  U.EMP_ID
			WHERE EE.EVU_EMP_ID = '00812' AND EE.EVU_STD_ID = '202201' 
		) T ON C.CHASU = T.CHASU

		UNION 

		SELECT 4 as CHASU,ET.EVU_TASK_SEQ AS EVU_MNG_SEQ , U.EMP_NM, U.EMP_ID, U.DUTY_CD, U.DUTY_NM, U.JOB_NM, ET.TASK_NM, ORG_ID,ORG_NM
		FROM EVU_TASK ET INNER JOIN EVU_EMP EE ON ET.EVU_EMP_NO = EE.EVU_EMP_NO 
			INNER JOIN [USER] U ON ET.TASK_MNG_ID = U.EMP_ID
		WHERE EE.EVU_EMP_ID =  '00812' AND EE.EVU_STD_ID  =  '202201'

11. /*나의 평가대상 상태별 카운트 selectEvuMngCnt2*/

		SELECT 
			COUNT(*) TOTAL_CNT,
			ISNULL(SUM(CASE WHEN MNG_STAT_CD='MB' THEN 1 ELSE 0 END), 0) BF_CNT,
			ISNULL(SUM(CASE WHEN MNG_STAT_CD='MI' THEN 1 ELSE 0 END), 0) ING_CNT,
			ISNULL(SUM(CASE WHEN MNG_STAT_CD='MD' THEN 1 ELSE 0 END), 0) DONE_CNT
		FROM (
			SELECT 
				CASE 
					WHEN (CHASU=3 AND MNG_STAT_CD='MD' AND PATINDEX('%1',CUR_STEP_CD) > 0) THEN 'MI'
					WHEN (EMP_CHASU > CHASU) THEN 'MD'
					ELSE MNG_STAT_CD
				END MNG_STAT_CD
			FROM (
				SELECT 
					MNG.EVU_MNG_SEQ,
					MNG.EVU_MNG_ID,
					MNG.CHASU, 
					MNG.MNG_STAT_CD, 
					EMP.CUR_STEP_CD, 
					EMP.CHASU AS EMP_CHASU,
					EMP.EVU_EMP_ID,
					EMP.EVU_EMP_NO
				FROM EVU_MNG MNG INNER JOIN EVU_EMP EMP ON (MNG.EVU_EMP_NO = EMP.EVU_EMP_NO AND EMP.CUR_STEP_CD = 'D1' AND EMP.EVU_STD_ID = '202201')			
					LEFT JOIN EVU_STEP SP ON (EMP.CUR_STEP_CD = SP.EVU_STEP_CD AND SP.EVU_STD_ID = '202201')
				WHERE MNG.EVU_MNG_ID = '00812'
				UNION
				SELECT 
					ET.EVU_TASK_SEQ AS EVU_MNG_SEQ, 
					ET.TASK_MNG_ID AS EVU_MNG_ID,
					1 AS CHASU, 
					CASE 
						WHEN (ET.TASK_CFM_YN IS NULL OR ET.TASK_CFM_YN ='N') THEN 'MB'
						ELSE 'MD' 
					END AS MNG_STAT_CD,
					EMP.CUR_STEP_CD, 
					EMP.CHASU AS EMP_CHASU,
					EMP.EVU_EMP_ID,
					EMP.EVU_EMP_NO
				FROM EVU_TASK ET INNER JOIN EVU_EMP EMP ON (ET.EVU_EMP_NO = EMP.EVU_EMP_NO  AND EMP.CUR_STEP_CD = 'D1' AND EMP.EVU_STD_ID = '202201')
				WHERE ET.TASK_MNG_ID = '00812' AND  ET.EVU_STD_ID = '202201'
			) R INNER JOIN [USER] U ON (R.EVU_EMP_ID = U.EMP_ID) 
			WHERE R.CHASU = ISNULL(ISNULL((SELECT MIN(CHASU) 
									FROM EVU_MNG 
									WHERE EVU_MNG_ID=R.EVU_MNG_ID 
									AND EVU_EMP_NO = R.EVU_EMP_NO 
									AND CHASU >=R.EMP_CHASU), 
									(SELECT MAX(CHASU) 
									FROM EVU_MNG WHERE EVU_MNG_ID=R.EVU_MNG_ID
									AND EVU_EMP_NO = R.EVU_EMP_NO
									AND CHASU < R.EMP_CHASU)),1)
		) A


11. SELECT NOTI_NO, NOTI_IMPORTANT, NOTI_SUBJECT, NOTI_CONTENT,
		NOTI_HIT, INS_YMDHMS , ROW_NUMBER() OVER( ORDER BY NOTI_IMPORTANT ASC, NOTI_NO ASC ) AS R_NUM FROM NOTI_BOARD 

		ORDER BY NOTI_IMPORTANT DESC, NOTI_NO DESC  OFFSET ( 1 - 1 ) ROWS FETCH NEXT 6 ROWS ONLY

11. /* selectMainResultPopStep */

		SELECT R.EVU_STEP_CD+','+R.EVU_STD_ID AS EVU_STEP_CD, R.EVU_STD_ID,R.EVU_STEP_NM, R.ORDER_NO, R.EVU_STD_NM
		FROM (
			SELECT S.EVU_STEP_CD, S.EVU_STD_ID,S.EVU_STEP_NM ,S.ORDER_NO,S.EVU_YY AS EVU_STD_NM,
				CASE WHEN SUBSTRING(S.EVU_STEP_CD, 1, 1) = 'B' THEN CFM_STAT_CD_1Q
					 WHEN SUBSTRING(S.EVU_STEP_CD, 1, 1) = 'C' THEN CFM_STAT_CD_2Q
					 WHEN SUBSTRING(S.EVU_STEP_CD, 1, 1) = 'D' THEN CFM_STAT_CD_3Q
					 WHEN SUBSTRING(S.EVU_STEP_CD, 1, 1) = 'E' THEN CFM_STAT_CD_4Q
				ELSE NULL END STAT_CD
			FROM 

			(select B.EVU_STD_ID,A.EVU_YY,B.EVU_STEP_CD,B.EVU_STEP_NM,B.EVU_OPEN_YN,B.ORDER_NO from EVU_STD A LEFT JOIN EVU_STEP B ON(A.EVU_STD_ID = B.EVU_STD_ID)) S INNER JOIN EVU_EMP E 
			ON (S.EVU_STD_ID = E.EVU_STD_ID AND E.EVU_EMP_NO IN (SELECT EVU_EMP_NO FROM EVU_EMP WHERE EVU_EMP_ID = '00812'))
			WHERE S.EVU_OPEN_YN ='Y' 
		) R WHERE R.EVU_STEP_CD LIKE '%1'
		AND STAT_CD = 'MC' 
		ORDER BY R.EVU_STD_NM DESC, R.ORDER_NO DESC

11. /* selectResultTot */
		SELECT ET.EVU_TYPE, EE.EVU_EMP_NO, EE.EVU_EMP_ID

		 ,MNG1_GRD_2Q AS MNG1_GRD, MNG1_COMNT_2Q AS MNG1_COMNT, MNG2_GRD_2Q MNG2_GRD, MNG2_COMNT_2Q AS MNG2_COMNT, TOT_COMNT_2Q AS TOT_COMNT, TOT_CFM_GRD_2Q AS TOT_GRD 

		FROM EVU_TOT ET INNER JOIN EVU_EMP EE ON ET.EVU_EMP_NO = EE.EVU_EMP_NO AND EVU_STD_ID= '202201'
		WHERE EE.EVU_EMP_ID = '00812' 
		ORDER BY ET.EVU_TOT_SEQ DESC

11. SELECT 
			COUNT(*)
		FROM 
			EVU_BIS_AUTH
		WHERE 
			EVU_MNG_ID = '00812' AND EVU_STD_ID = '202201'

11. SELECT 
			COUNT(*)
		FROM 
			ADMIN_PER_AUTH
		WHERE 
			EVU_MNG_ID = '00812' AND EVU_STD_ID = '202201'

11. SELECT PC.* FROM (
		SELECT  ROW_NUMBER() OVER(PARTITION BY PB.EVU_MNG_ID, PB.EVU_EMP_NO ORDER BY ( CASE WHEN PB.EMP_CHASU = 1 OR PB.EMP_CHASU = 2 THEN PB.RNum WHEN PB.EMP_CHASU = 3 THEN PB.CHASU END ) DESC ) AS RNm, PB.* FROM (
		SELECT  ROW_NUMBER() OVER(PARTITION BY PA.EVU_MNG_ID, PA.EVU_EMP_NO ORDER BY PA.CHASU DESC ) AS RNum ,PA.* FROM (
		SELECT
			D.EMP_NM , D.POST_NM, D.POST_CD, D.POST_AGE AS GRADE_STA_YEAR, A.CHASU, D.ENTER_YMD,
			B.CHASU AS EMP_CHASU, convert(varchar(10), B.CON_START_DATE, 120) AS CON_START_DATE,
			convert(varchar(10), B.CON_END_DATE, 120) AS CON_END_DATE,
			CASE WHEN DATEDIFF(dd, GETDATE(), B.CON_END_DATE ) + 1 > 0 THEN DATEDIFF(dd, GETDATE(), B.CON_END_DATE ) + 1
			WHEN 0 > DATEDIFF(dd, GETDATE(), B.CON_END_DATE ) + 1 THEN 0
			ELSE 0 END AS CON_DDAY,
			CASE WHEN B.CHASU = 0 THEN '업적입력'
			WHEN B.CHASU = 1 AND B.EVU_STAT_CD = 'MI' THEN '1차평가'
			WHEN B.CHASU = 1 AND B.EVU_STAT_CD = 'MC' THEN '평가완료'
			WHEN B.CHASU = 2 AND B.EVU_STAT_CD = 'MI' THEN '2차평가'
			WHEN B.CHASU = 2 AND B.EVU_STAT_CD = 'MC' THEN '평가완료'
			WHEN B.CHASU = 3 AND B.EVU_STAT_CD = 'MI' THEN '최종평가'
			WHEN B.CHASU = 3 AND ( B.EVU_STAT_CD = 'MD' OR B.EVU_STAT_CD = 'MC' )  THEN '평가완료'
			ELSE '' END AS EVU_STAT_NM
			, CO.SEQ_NO
			, CO.DEPTH
			, CO.OBJ_NM ORG_NM_TREE1
			, CO.PAR_OBJ_NM ORG_NM_TREE2
			, CO.PAR_OBJ_NM3 ORG_NM_TREE3
			,D.JOB_NM, CO.PAR_OBJ_NM2 PAR_OBJ_NM2, CO.PAR_OBJ_NM ORG_NM, D.ORG_NM PAR_ORG_NM
			,A.MNG_STAT_CD, E.MNG1_GRD, E.MNG2_GRD, E.TOT_GRD
			,B.EVU_STAT_CD, B.CDP_CD, B.EVU2_YN, B.PM_YN, B.MNG1_PM_YN, B.MNG2_PM_YN, B.MNG3_PM_YN 
			, B.EVU_EMP_NO, B.EVU_STD_ID, B.EVU_EMP_ID
			,B.CFM_STAT_CD, B.ASSE_OPEN_YN, B.OPEN_YN, 
			CASE WHEN B.APPNT_CD = '계약직' AND  D.POST_CD IN ('GBS1', 'GB1', 'GB2', 'GB3', 'GB4', 'GB5') THEN '지원직군'
			WHEN B.APPNT_CD = '계약직' AND  D.POST_CD IN ( 'GG1','GG2','GG3' ) THEN '경영관리직군'
			ELSE '면수습' END AS APPNT_CD
			,E.EVU_TOT_SEQ, A.EVU_MNG_ID
		FROM CON_EVU_MNG A 
			LEFT JOIN CON_EVU_TOT E
				ON A.EVU_EMP_NO = E.EVU_EMP_NO
			, CON_EVU_EMP B
			, EVU_STD C
			, [USER] D	
			LEFT JOIN COMM_ORG_VIEW CO
				 ON (CO.OBJ_ID = D.ORG_ID)

				WHERE A.EVU_EMP_NO = B.EVU_EMP_NO
					AND A.CHASU > 0
					AND B.EVU_EMP_ID = D.EMP_ID 
					AND B.EVU_STD_ID = C.EVU_STD_ID	

						AND A.EVU_MNG_ID = '00812'

		) PA ) PB ) PC
		WHERE PC.RNm = 1
		ORDER BY PC.EVU_EMP_NO DESC
