CREATE TABLE wondermom89_mj89ya.dbo.ADMIN_PER (
	ADMIN_PER_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_EMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_STD_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	SCORE int NULL,
	[RANK] int NULL,
	RESULT_TYPE varchar(2) COLLATE Korean_Wansung_CI_AI NULL,
	COMMENT text COLLATE Korean_Wansung_CI_AI NULL,
	ACHIEVEMENT text COLLATE Korean_Wansung_CI_AI NULL,
	CAPABILITY text COLLATE Korean_Wansung_CI_AI NULL,
	PROMOTE text COLLATE Korean_Wansung_CI_AI NULL,
	CARRER text COLLATE Korean_Wansung_CI_AI NULL,
	CAPA_POINT float DEFAULT 0 NULL,
	PROBLEM_POINT float DEFAULT 0 NULL,
	COMM_POINT float DEFAULT 0 NULL,
	PEOPLE_POINT float DEFAULT 0 NULL,
	READY_POINT float DEFAULT 0 NULL,
	READY_TYPE varchar(4) COLLATE Korean_Wansung_CI_AI NULL,
	STRENGTH text COLLATE Korean_Wansung_CI_AI NULL,
	SUPPLEMENT text COLLATE Korean_Wansung_CI_AI NULL,
	Y18_PGRD varchar(2) COLLATE Korean_Wansung_CI_AI NULL,
	Y18_CGRD varchar(2) COLLATE Korean_Wansung_CI_AI NULL,
	Y17_PGRD varchar(2) COLLATE Korean_Wansung_CI_AI NULL,
	Y17_CGRD varchar(2) COLLATE Korean_Wansung_CI_AI NULL,
	Y17_OGRD varchar(2) COLLATE Korean_Wansung_CI_AI NULL,
	NEED text COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	RE_YN varchar(2) COLLATE Korean_Wansung_CI_AI NULL,
	SKILL_POINT float DEFAULT 0 NULL,
	LEADER_POINT float DEFAULT 0 NULL,
	LEADING_POINT float DEFAULT 0 NULL,
	SACRIFICE_POINT float DEFAULT 0 NULL,
	CHANGE_POINT float DEFAULT 0 NULL,
	RECOMMEND text COLLATE Korean_Wansung_CI_AI NULL,
	CONSTRAINT PK_ADMIN_PER PRIMARY KEY (ADMIN_PER_SEQ)
);


CREATE TABLE wondermom89_mj89ya.dbo.ADMIN_PER_AUTH (
	ADMIN_PER_AUTH_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_EMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_MNG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_STD_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL
);

CREATE TABLE wondermom89_mj89ya.dbo.BOARD_FILE (
	BF_NO int IDENTITY(1,1) NOT NULL,
	BF_BOARD_TYPE char(1) COLLATE Korean_Wansung_CI_AI NULL,
	BF_BOARD_NO int NULL,
	BF_ORG_FILENAME varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	BF_FILENAME varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	BF_INS_USERID varchar(10) COLLATE Korean_Wansung_CI_AI NULL,
	BF_INS_YMDHMS datetime NULL,
	BF_MOD_USERID varchar(10) COLLATE Korean_Wansung_CI_AI NULL,
	BF_MOD_YMDHMS datetime NULL
);


CREATE TABLE wondermom89_mj89ya.dbo.COMM_GRADE (
	IDX_CD varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CD varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CD_NM varchar(100) COLLATE Korean_Wansung_CI_AI NOT NULL,
	DP_ORDER int NOT NULL,
	SMR_CD_NM varchar(200) COLLATE Korean_Wansung_CI_AI NULL,
	ENG_NM varchar(500) COLLATE Korean_Wansung_CI_AI NULL,
	CNVT_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	STA_YMD date NULL,
	END_YMD date NULL,
	USE_YN char(1) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	CONSTRAINT PK_COMM_GRADE PRIMARY KEY (IDX_CD,CD)
);


CREATE TABLE wondermom89_mj89ya.dbo.COMM_ORG (
	OBJ_TYPE varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	OBJ_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	OBJ_NM varchar(100) COLLATE Korean_Wansung_CI_AI NOT NULL,
	SMR_OBJ_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	CHA_OBJ_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	ENG_OBJ_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	CHG_RSN_TXT varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	PAR_OBJ_TYPE varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	PAR_OBJ_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	STA_YMD date NOT NULL,
	END_YMD date NULL,
	SEQ_NO int NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	UPT_YMDHMS datetime NULL,
	CONSTRAINT PK_COMM_ORG PRIMARY KEY (OBJ_TYPE,OBJ_ID)
);



CREATE TABLE wondermom89_mj89ya.dbo.COMM_ORG_BATCH (
	OBJ_TYPE varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	OBJ_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	OBJ_NM varchar(100) COLLATE Korean_Wansung_CI_AI NOT NULL,
	SMR_OBJ_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	CHA_OBJ_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	ENG_OBJ_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	CHG_RSN_TXT varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	PAR_OBJ_TYPE varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	PAR_OBJ_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	STA_YMD date NOT NULL,
	END_YMD date NULL,
	SEQ_NO int NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	UPT_YMDHMS datetime NULL
);


CREATE TABLE wondermom89_mj89ya.dbo.CON_EVU_COMP (
	EVU_COMP_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_STD_ID varchar(6) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_CDP_COMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_EMP_NO int NOT NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	MNG1_SCORE char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_SCORE char(1) COLLATE Korean_Wansung_CI_AI NULL,
	TOT_SCORE char(1) COLLATE Korean_Wansung_CI_AI NULL
);

CREATE TABLE wondermom89_mj89ya.dbo.CON_EVU_EMP (
	EVU_EMP_NO int IDENTITY(1,1) NOT NULL,
	EVU_STD_ID varchar(50) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_STAT_CD char(2) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CHASU tinyint NULL,
	EVU_EMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CDP_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EVU2_YN char(1) COLLATE Korean_Wansung_CI_AI NOT NULL,
	PM_YN char(1) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_YMDHMS datetime NOT NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	MNG1_PM_YN char(1) COLLATE Korean_Wansung_CI_AI NOT NULL,
	APPLY_DATE datetime NULL,
	MNG_APPLY_DATE datetime NULL,
	MNG2_PM_YN char(1) COLLATE Korean_Wansung_CI_AI NOT NULL,
	MNG3_PM_YN char(1) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CFM_STAT_CD char(2) COLLATE Korean_Wansung_CI_AI NULL,
	ASSE_OPEN_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NULL,
	OPEN_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NULL,
	CON_START_DATE datetime NULL,
	CON_END_DATE datetime NULL,
	EXPOSURE_YN varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	APPNT_CD varchar(10) COLLATE Korean_Wansung_CI_AI NULL
);

CREATE TABLE wondermom89_mj89ya.dbo.CON_EVU_MNG (
	EVU_MNG_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_MNG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_EMP_NO varchar(50) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CHASU tinyint NOT NULL,
	APPLY_DATE datetime NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_YMDHMS datetime NOT NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	MNG_STAT_CD char(2) COLLATE Korean_Wansung_CI_AI NOT NULL,
	TEMPORARY_YN char(1) COLLATE Korean_Wansung_CI_AI NULL
);


CREATE TABLE wondermom89_mj89ya.dbo.CON_EVU_TASK (
	EVU_TASK_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_STD_ID varchar(8) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_EMP_NO int NOT NULL,
	TASK_NM varchar(4000) COLLATE Korean_Wansung_CI_AI NULL,
	EXEC_PLAN text COLLATE Korean_Wansung_CI_AI NULL,
	TASK_MNG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	MNG1_ACHV_RATE char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_ACHV_RATE char(1) COLLATE Korean_Wansung_CI_AI NULL,
	TOT_ACHV_RATE char(1) COLLATE Korean_Wansung_CI_AI NULL
);

CREATE TABLE ㅍ.dbo.CON_EVU_TOT (
	EVU_TOT_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_EMP_NO int NOT NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_YMDHMS datetime NOT NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	MNG1_GRD char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_RE_CONTRACT char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_COMNT text COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_GRD char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_RE_CONTRACT char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_COMNT text COLLATE Korean_Wansung_CI_AI NULL,
	TOT_GRD char(1) COLLATE Korean_Wansung_CI_AI NULL,
	TOT_RE_CONTRACT char(1) COLLATE Korean_Wansung_CI_AI NULL,
	TOT_COMNT text COLLATE Korean_Wansung_CI_AI NULL
);


--이 테이블은 모르겠다. 
CREATE TABLE wondermom89_mj89ya.dbo.EVU_BIS_AUTH (
	BIS_AUTH_SEQ int NOT NULL,
	EVU_EMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_MNG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_STD_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL
);


CREATE TABLE wondermom89_mj89ya.dbo.EVU_CDP (
	EVU_CDP_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_STD_ID varchar(6) COLLATE Korean_Wansung_CI_AI NULL,
	CDP_CD varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	CDP_NM varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	CDP_MISSION text COLLATE Korean_Wansung_CI_AI NULL,
	CDP_TYPE char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'T' NULL,
	DP_ORDER int NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	POST_CD varchar(3) COLLATE Korean_Wansung_CI_AI DEFAULT 'NN' NOT NULL,
	CONSTRAINT PK_EVU_CDP PRIMARY KEY (EVU_CDP_SEQ)
);
 CREATE NONCLUSTERED INDEX IX_EVU_CDP_CD ON dbo.EVU_CDP (  CDP_CD ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_EVU_CDP_STDID ON dbo.EVU_CDP (  EVU_STD_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;

	
CREATE TABLE wondermom89_mj89ya.dbo.EVU_CDP_COMP (
	EVU_CDP_COMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_STD_ID varchar(50) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_CDP_CD varchar(50) COLLATE Korean_Wansung_CI_AI NOT NULL,
	POST_CD varchar(3) COLLATE Korean_Wansung_CI_AI DEFAULT 'NN' NOT NULL,
	CATE_CD1 char(7) COLLATE Korean_Wansung_CI_AI NULL,
	CATE_CD2 char(7) COLLATE Korean_Wansung_CI_AI NULL,
	CATE_CD3 char(7) COLLATE Korean_Wansung_CI_AI NULL,
	ACT_DESC text COLLATE Korean_Wansung_CI_AI NULL,
	SCORE int NULL,
	PRIORITY int NULL,
	DP_ORDER int NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	EVU_COMP_DEFINE_SEQ int NULL,
	DEFINE_CD varchar(7) COLLATE Korean_Wansung_CI_AI NULL,
	VISIBLE char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'Y' NULL,
	CONSTRAINT PK_EVU_CDP_COMP PRIMARY KEY (EVU_CDP_COMP_ID)
);
 CREATE NONCLUSTERED INDEX IX_EVU_CDP_COMP_CDPCD ON dbo.EVU_CDP_COMP (  EVU_CDP_CD ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_EVU_CDP_COMP_DEFINECD ON dbo.EVU_CDP_COMP (  DEFINE_CD ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_EVU_CDP_COMP_STDID ON dbo.EVU_CDP_COMP (  EVU_STD_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;	

-- skgas.dbo.EVU_COMP definition

-- Drop table

-- DROP TABLE skgas.dbo.EVU_COMP;

CREATE TABLE wondermom89_mj89ya.dbo.EVU_COMP (
	EVU_COMP_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_STD_ID varchar(6) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_CDP_COMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_EMP_NO int NOT NULL,
	SELF_SCORE_1Q tinyint NULL,
	MNG1_SCORE_1Q tinyint NULL,
	MNG2_SCORE_1Q tinyint NULL,
	SELF_SCORE_2Q tinyint NULL,
	MNG1_SCORE_2Q tinyint NULL,
	MNG2_SCORE_2Q tinyint NULL,
	SELF_SCORE_3Q tinyint NULL,
	MNG1_SCORE_3Q tinyint NULL,
	MNG2_SCORE_3Q tinyint NULL,
	SELF_SCORE_4Q tinyint NULL,
	MNG1_SCORE_4Q tinyint NULL,
	MNG2_SCORE_4Q tinyint NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	MNG1_AF_SCORE_1Q tinyint NULL,
	MNG1_AF_SCORE_2Q tinyint NULL,
	MNG1_AF_SCORE_3Q tinyint NULL,
	MNG1_AF_SCORE_4Q tinyint NULL,
	MNG2_AF_SCORE_3Q tinyint NULL,
	CONSTRAINT PK_EVU_COMP PRIMARY KEY (EVU_COMP_SEQ)
);
 CREATE NONCLUSTERED INDEX IX_EVU_COMP_COMPID ON dbo.EVU_COMP (  EVU_CDP_COMP_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_EVU_COMP_EMPNO ON dbo.EVU_COMP (  EVU_EMP_NO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_EVU_COMP_STDID ON dbo.EVU_COMP (  EVU_STD_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
	
	
CREATE TABLE wondermom89_mj89ya.dbo.EVU_COMP_CATE (
	EVU_COMP_CATE_SEQ int IDENTITY(1,1) NOT NULL,
	CATE_NM varchar(256) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CATE_CD char(7) COLLATE Korean_Wansung_CI_AI NOT NULL,
	[DEPTH] tinyint NOT NULL,
	PARENT_SEQ int NULL,
	WT_SCORE int NOT NULL,
	DP_ORDER int NOT NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_YMDHMS datetime NOT NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	VISIBLE char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_EVU_COMP_CATE PRIMARY KEY (EVU_COMP_CATE_SEQ)
);
 CREATE NONCLUSTERED INDEX IX_EVU_COMP_CATE ON dbo.EVU_COMP_CATE (  CATE_CD ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
	
	

CREATE TABLE wondermom89_mj89ya.dbo.EVU_COMP_DEFINE (
	EVU_COMP_DEFINE_SEQ int IDENTITY(1,1) NOT NULL,
	DEFINE_CD varchar(7) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CATE_CD1 char(7) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CATE_CD2 char(7) COLLATE Korean_Wansung_CI_AI NULL,
	CATE_CD3 char(7) COLLATE Korean_Wansung_CI_AI NULL,
	COMP_TITLE varchar(50) COLLATE Korean_Wansung_CI_AI NOT NULL,
	COMP_DEFINE text COLLATE Korean_Wansung_CI_AI NOT NULL,
	DP_ORDER int DEFAULT 0 NULL,
	VISIBLE char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NULL,
	PRIORITY tinyint DEFAULT 0 NULL,
	CUSTOM_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	CONSTRAINT PK_EVU_COMP_DEFINE PRIMARY KEY (EVU_COMP_DEFINE_SEQ)
);
 CREATE NONCLUSTERED INDEX IX_EVU_COMP_DEFINE_CATE1 ON dbo.EVU_COMP_DEFINE (  CATE_CD1 ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_EVU_COMP_DEFINE_CATE2 ON dbo.EVU_COMP_DEFINE (  CATE_CD2 ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_EVU_COMP_DEFINE_CATE3 ON dbo.EVU_COMP_DEFINE (  CATE_CD3 ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_EVU_COMP_DEFINE_CD ON dbo.EVU_COMP_DEFINE (  DEFINE_CD ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
	
CREATE TABLE wondermom89_mj89ya.dbo.EVU_COMP_LAST (
	seq int IDENTITY(1,1) NOT NULL,
	EVU_EMP_ID varchar(6) COLLATE Korean_Wansung_CI_AI NULL,
	COMP_TITLE varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	COMP_DEFINE text COLLATE Korean_Wansung_CI_AI NULL,
	MNG_SCORE_2Q varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_SCORE_3Q varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_AF_SCORE_3Q varchar(10) COLLATE Korean_Wansung_CI_AI NULL,
	IS_PRIORITY int NULL,
	IS_CUSTOM char(1) COLLATE Korean_Wansung_CI_AI NULL,
	CATE_CD1 varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	DP_ORDER int NULL,
	INS_YMDHMS datetime NULL
);
 CREATE NONCLUSTERED INDEX IX_EVU_COMP_LAST_EMPID ON dbo.EVU_COMP_LAST (  EVU_EMP_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
	
	
CREATE TABLE wondermom89_mj89ya.dbo.EVU_EMP (
	EVU_EMP_NO int IDENTITY(1,1) NOT NULL,
	EVU_STD_ID varchar(50) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CUR_STEP_CD char(2) COLLATE Korean_Wansung_CI_AI DEFAULT 'A0' NOT NULL,
	EVU_STAT_CD char(2) COLLATE Korean_Wansung_CI_AI DEFAULT 'EI' NOT NULL,
	CHASU tinyint DEFAULT 0 NULL,
	EVU_EMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CDP_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EVU2_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	PM_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	COMP_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	MOVE_PERIOD_CD char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MOVE_WISH_ORG_ID_1 varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOVE_WISH_ORG_ID_2 varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOVE_WISH_ORG_ID_3 varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOVE_WISH_COMNT varchar(1000) COLLATE Korean_Wansung_CI_AI NULL,
	MOVE_WISH_EVU_COMNT varchar(1000) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_YMDHMS datetime NOT NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	MNG1_PM_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	MNG1_COMP_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	APPLY_DATE datetime NULL,
	MNG_APPLY_DATE datetime NULL,
	MNG2_PM_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	MNG2_COMP_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	MNG3_PM_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	MNG3_COMP_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	CFM_STAT_CD_1Q char(2) COLLATE Korean_Wansung_CI_AI NULL,
	CFM_STAT_CD_2Q char(2) COLLATE Korean_Wansung_CI_AI NULL,
	CFM_STAT_CD_3Q char(2) COLLATE Korean_Wansung_CI_AI NULL,
	CFM_STAT_CD_4Q char(2) COLLATE Korean_Wansung_CI_AI NULL,
	REVIEW_PM_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NULL,
	REVIEW_COMP_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NULL,
	EMP_ORG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	CONSTRAINT PK_EVU_EMP PRIMARY KEY (EVU_EMP_NO)
);
 CREATE NONCLUSTERED INDEX IX_EVU_EMP_EMPID ON dbo.EVU_EMP (  EVU_EMP_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_EVU_EMP_STDID ON dbo.EVU_EMP (  EVU_STD_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_EVU_EMP_STEPCD ON dbo.EVU_EMP (  CUR_STEP_CD ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;	
	
CREATE TABLE wondermom89_mj89ya.dbo.EVU_EMP_CDP (
	EVU_EMP_CDP_SEQ int NOT NULL,
	EVU_EMP_NO int NOT NULL,
	STEP_CD varchar(3) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_STD_ID varchar(6) COLLATE Korean_Wansung_CI_AI NULL,
	CDP_CD varchar(6) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_YMDHMS datetime NOT NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL
);

CREATE TABLE wondermom89_mj89ya.dbo.EVU_EMP_STATUS (
	EVU_EMP_STATUS_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_STD_ID varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	CUR_STEP_CD char(2) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_EMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_MNG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	CONSTRAINT PK_EVU_EMP_STATUS PRIMARY KEY (EVU_EMP_STATUS_SEQ)
);

CREATE TABLE wondermom89_mj89ya.dbo.EVU_FEEDBACK (
	EVU_FEEDBACK_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_EMP_NO int NOT NULL,
	MNG1_ADVANTEGE_1Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_IMPROVE_1Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_DONE_1Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_RESULT_1Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_CDP_CD_1Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_CDP_TEXT_1Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC1_ID_1Q varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC1_NAME_1Q varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC1_TEXT_1Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC2_ID_1Q varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC2_NAME_1Q varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC2_TEXT_1Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_ADVANTEGE_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_IMPROVE_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_DONE_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_RESULT_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_CDP_CD_2Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_CDP_TEXT_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC1_ID_2Q varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC1_NAME_2Q varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC1_TEXT_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC2_ID_2Q varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC2_NAME_2Q varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC2_TEXT_2Q varchar(500) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_ADVANTEGE_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_IMPROVE_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_DONE_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_RESULT_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_ADVANTEGE_3Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_IMPROVE_3Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_DONE_3Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_RESULT_3Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_CDP_CD_3Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_CDP_TEXT_3Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC1_ID_3Q varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC1_NAME_3Q varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC1_TEXT_3Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC2_ID_3Q varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC2_NAME_3Q varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_SUCC2_TEXT_3Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_YMDHMS datetime NOT NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	CONSTRAINT PK_EVU_FEEDBACK PRIMARY KEY (EVU_FEEDBACK_SEQ)
);
 CREATE NONCLUSTERED INDEX IX_EVU_FEEDBACK ON dbo.EVU_FEEDBACK (  EVU_FEEDBACK_SEQ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_EVU_FEEDBACK_EMPNO ON dbo.EVU_FEEDBACK (  EVU_EMP_NO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


CREATE TABLE wondermom89_mj89ya.dbo.EVU_FEEDBACK_LAST (
	SEQ int IDENTITY(1,1) NOT NULL,
	EVU_EMP_ID varchar(6) COLLATE Korean_Wansung_CI_AI NOT NULL,
	MNG_ADVANTEGE_1Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_IMPROVE_1Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_DONE_1Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_RESULT_1Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_ADVANTEGE_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_IMPROVE_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_DONE_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_RESULT_2Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_ADVANTEGE_3Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_IMPROVE_3Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_DONE_3Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_RESULT_3Q varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	CDP_CD varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	CDP_TEXT varchar(1024) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_SUCC1_NAME varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_SUCC2_NAME varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL
);
 CREATE NONCLUSTERED INDEX IX_EVU_FEEDBACK_LAST_EMPID ON dbo.EVU_FEEDBACK_LAST (  EVU_EMP_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;	

	
	
CREATE TABLE wondermom89_mj89ya.dbo.EVU_FILE (
	EVU_TASK_FILE_SEQ int IDENTITY(1,1) NOT NULL,
	EMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_STD_ID varchar(6) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_STEP_CD char(2) COLLATE Korean_Wansung_CI_AI NULL,
	REL_FILE_PATH varchar(512) COLLATE Korean_Wansung_CI_AI NULL,
	CONTENT_TYPE varchar(512) COLLATE Korean_Wansung_CI_AI NULL,
	FILE_SIZE int NULL,
	FILE_NM varchar(512) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	CONSTRAINT PK_EVU_TASK_FILE PRIMARY KEY (EVU_TASK_FILE_SEQ)
);

 CREATE NONCLUSTERED INDEX NonClusteredIndex_20190622_144104 ON dbo.EVU_FILE (  EVU_STD_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX NonClusteredIndex_20190622_144114 ON dbo.EVU_FILE (  EMP_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;	
	
	

CREATE TABLE wondermom89_mj89ya.dbo.EVU_ITEM (
	ITEM_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_STD_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	ITEM_NM varchar(1000) COLLATE Korean_Wansung_CI_AI NOT NULL,
	ITEM_DETAIL_NM varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	ITEM_TYPE varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	GRD_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_YMDHMS datetime NOT NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	DP_ORDER int DEFAULT 0 NOT NULL
);


CREATE TABLE wondermom89_mj89ya.dbo.EVU_MNG (
	EVU_MNG_SEQ int NOT NULL,
	EVU_MNG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_EMP_NO varchar(50) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CHASU tinyint NOT NULL,
	MNG_ORG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MNG_ORG_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	APPLY_DATE datetime NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_YMDHMS datetime NOT NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	MNG_STAT_CD char(2) COLLATE Korean_Wansung_CI_AI DEFAULT 'MB' NOT NULL,
	TEMPORARY_YN char(1) COLLATE Korean_Wansung_CI_AI NULL
);

CREATE TABLE wondermom89_mj89ya.dbo.EVU_STAT (
	EVU_STAT_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_STEP_CD char(2) COLLATE Korean_Wansung_CI_AI NULL,
	CHASU tinyint NULL,
	EVU_STAT_NM varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_STAT_CD char(2) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_STAT_CL varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	CONSTRAINT PK_EVU_STAT PRIMARY KEY (EVU_STAT_SEQ)
);
 CREATE NONCLUSTERED INDEX NonClusteredIndex_20190622_144205 ON dbo.EVU_STAT (  EVU_STEP_CD ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX NonClusteredIndex_20190622_144214 ON dbo.EVU_STAT (  EVU_STAT_CD ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX NonClusteredIndex_20190622_144228 ON dbo.EVU_STAT (  CHASU ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


CREATE TABLE wondermom89_mj89ya.dbo.EVU_STD (
	EVU_STD_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_STD_NM varchar(100) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_YY int NOT NULL,
	EVU_TIME_CD char(3) COLLATE Korean_Wansung_CI_AI NOT NULL,
	STA_YMD date NOT NULL,
	END_YMD date NOT NULL,
	PM_WT int NOT NULL,
	COMP_WT int NOT NULL,
	EVU_RSLT_OPEN_YN char(1) COLLATE Korean_Wansung_CI_AI NOT NULL,
	OPEN_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_YMDHMS datetime NOT NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	CONSTRAINT PK_EVU_STD PRIMARY KEY (EVU_STD_ID)
);


CREATE TABLE wondermom89_mj89ya.dbo.EVU_STEP (
	EVU_STEP_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_STD_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_STEP_CD char(2) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_STEP_NM varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	EVU_SDATE date NULL,
	EVU_EDATE date NULL,
	ETC_EVU_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	EVU_OPEN_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	ORDER_NO int NULL,
	ORG_FILE_NAME varchar(255) COLLATE Korean_Wansung_CI_AI NULL,
	ASSE_OPEN_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	COMP_ITEM_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NULL,
	COMP_RESULT_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NULL,
	COMP_FEEDBACK_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NULL,
	COMP_TOT_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	CONSTRAINT PK_EVU_STEP PRIMARY KEY (EVU_STEP_SEQ),
	CONSTRAINT FK_EVU_STEP_EVU_STD_ID_EVU_STD_EVU_STD_ID FOREIGN KEY (EVU_STD_ID) REFERENCES wondermom89_mj89ya.dbo.EVU_STD(EVU_STD_ID)
);
 CREATE NONCLUSTERED INDEX NonClusteredIndex_20190622_144307 ON dbo.EVU_STEP (  EVU_STD_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX NonClusteredIndex_20190622_144317 ON dbo.EVU_STEP (  EVU_STEP_CD ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;

	
CREATE TABLE wondermom89_mj89ya.dbo.EVU_TASK (
	EVU_TASK_SEQ int NOT NULL,
	EVU_STD_ID varchar(8) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_EMP_NO int NOT NULL,
	EVU_TYPE char(1) COLLATE Korean_Wansung_CI_AI NOT NULL,
	WT_SCORE int NULL,
	TASK_NM varchar(4000) COLLATE Korean_Wansung_CI_AI NULL,
	EXEC_PLAN text COLLATE Korean_Wansung_CI_AI NULL,
	EXEC_PLAN_LONG text COLLATE Korean_Wansung_CI_AI NULL,
	EXEC_PLAN_COMNT text COLLATE Korean_Wansung_CI_AI NULL,
	TASK_MNG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_ACHV_RATE_1Q int NULL,
	SELF_ACHV_TEXT_1Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_ACHV_RATE_1Q int NULL,
	MNG1_ACHV_TEXT_1Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_ACHV_RATE_1Q int NULL,
	MNG2_ACHV_TEXT_1Q text COLLATE Korean_Wansung_CI_AI NULL,
	SELF_ACHV_RATE_2Q int NULL,
	SELF_ACHV_TEXT_2Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_ACHV_RATE_2Q int NULL,
	MNG1_ACHV_TEXT_2Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_ACHV_RATE_2Q int NULL,
	MNG2_ACHV_TEXT_2Q text COLLATE Korean_Wansung_CI_AI NULL,
	SELF_ACHV_RATE_3Q int NULL,
	SELF_ACHV_TEXT_3Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_ACHV_RATE_3Q int NULL,
	MNG1_ACHV_TEXT_3Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_ACHV_RATE_3Q int NULL,
	MNG2_ACHV_TEXT_3Q text COLLATE Korean_Wansung_CI_AI NULL,
	SELF_ACHV_RATE_4Q int NULL,
	SELF_ACHV_TEXT_4Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_ACHV_RATE_4Q int NULL,
	MNG1_ACHV_TEXT_4Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_ACHV_RATE_4Q int NULL,
	MNG2_ACHV_TEXT_4Q text COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	TASK_CFM_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL
);	


CREATE TABLE wondermom89_mj89ya.dbo.EVU_TOT (
	EVU_TOT_SEQ int NOT NULL,
	EVU_EMP_NO int NOT NULL,
	EVU_TYPE char(1) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_RANK int DEFAULT 0 NOT NULL,
	ITEM_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_COMNT text COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_COMNT text COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_COMNT text COLLATE Korean_Wansung_CI_AI NULL,
	TOT_GRD char(1) COLLATE Korean_Wansung_CI_AI NULL,
	TOT_COMNT text COLLATE Korean_Wansung_CI_AI NULL,
	SELF_GRD_1Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_COMNT_1Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_GRD_1Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_COMNT_1Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_GRD_1Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_COMNT_1Q text COLLATE Korean_Wansung_CI_AI NULL,
	TOT_GRD_1Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	TOT_COMNT_1Q text COLLATE Korean_Wansung_CI_AI NULL,
	TOT_CFM_GRD_1Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_GRD_2Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_COMNT_2Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_GRD_2Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_COMNT_2Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_GRD_2Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_COMNT_2Q text COLLATE Korean_Wansung_CI_AI NULL,
	TOT_GRD_2Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	TOT_COMNT_2Q text COLLATE Korean_Wansung_CI_AI NULL,
	TOT_CFM_GRD_2Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_GRD_3Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_COMNT_3Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_GRD_3Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_COMNT_3Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_GRD_3Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_COMNT_3Q text COLLATE Korean_Wansung_CI_AI NULL,
	TOT_GRD_3Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	TOT_COMNT_3Q text COLLATE Korean_Wansung_CI_AI NULL,
	TOT_CFM_GRD_3Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_GRD_4Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	SELF_COMNT_4Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_GRD_4Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG1_COMNT_4Q text COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_GRD_4Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	MNG2_COMNT_4Q text COLLATE Korean_Wansung_CI_AI NULL,
	TOT_GRD_4Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	TOT_COMNT_4Q text COLLATE Korean_Wansung_CI_AI NULL,
	TOT_CFM_GRD_4Q char(1) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_YMDHMS datetime NOT NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	EVU_RANK_1Q int NULL,
	EVU_RANK_2Q int NULL,
	EVU_RANK_3Q int NULL,
	EVU_RANK_4Q int NULL,
	CONSTRAINT PK_EVU_TOT PRIMARY KEY (EVU_TOT_SEQ)
);
CREATE NONCLUSTERED INDEX IX_EVU_TOT_EMPNO ON wondermom89_mj89ya.dbo.EVU_TOT (EVU_EMP_NO);
CREATE NONCLUSTERED INDEX IX_EVU_TOT_EVUTYPE ON wondermom89_mj89ya.dbo.EVU_TOT (EVU_TYPE);


CREATE TABLE wondermom89_mj89ya.dbo.FAQ_BOARD (
	FAQ_NO int IDENTITY(1,1) NOT NULL,
	FAQ_CATEGORY int NULL,
	FAQ_SUBJECT varchar(255) COLLATE Korean_Wansung_CI_AI NULL,
	FAQ_CONTENT text COLLATE Korean_Wansung_CI_AI NULL,
	FAQ_SHOW_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'Y' NOT NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	FAQ_DEL_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL
);

CREATE TABLE wondermom89_mj89ya.dbo.FAQ_CATEGORY (
	CATEGORY_NO int IDENTITY(1,1) NOT NULL,
	CATEGORY_RANK int NULL,
	CATEGORY_NAME varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	CATEGORY_DEL_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL
);


CREATE TABLE wondermom89_mj89ya.dbo.NOTI_BOARD (
	NOTI_NO int IDENTITY(1,1) NOT NULL,
	NOTI_IMPORTANT int NULL,
	NOTI_SUBJECT varchar(255) COLLATE Korean_Wansung_CI_AI NULL,
	NOTI_CONTENT text COLLATE Korean_Wansung_CI_AI NULL,
	NOTI_HIT int NULL,
	INS_USER_ID varchar(10) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS date NULL,
	MOD_USER_ID varchar(10) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS date NULL
);

CREATE TABLE wondermom89_mj89ya.dbo.QNA_BOARD (
	QNA_NO int IDENTITY(1,1) NOT NULL,
	QNA_QTYPE int NULL,
	QNA_ATYPE int NULL,
	QNA_SUBJECT varchar(255) COLLATE Korean_Wansung_CI_AI NULL,
	QNA_CONTENT text COLLATE Korean_Wansung_CI_AI NULL,
	QNA_FILENAME varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	QNA_ANSWER text COLLATE Korean_Wansung_CI_AI NULL,
	QNA_INS_ADATE date NULL,
	QNA_MOD_ADATE date NULL,
	QNA_INS_AUSER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	QNA_MOD_AUSER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	QNA_REAL_FILENAME varchar(100) COLLATE Korean_Wansung_CI_AI NULL
);


CREATE TABLE wondermom89_mj89ya.dbo.SESSION_EMP (
	SESSION_EMP_SEQ int IDENTITY(1,1) NOT NULL,
	EVU_STD_ID varchar(11) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EVU_EMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	SESSION_NM varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	ORG_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	POST_YEAR varchar(200) COLLATE Korean_Wansung_CI_AI NULL,
	CAREER varchar(1000) COLLATE Korean_Wansung_CI_AI NULL,
	SUMMARY varchar(1000) COLLATE Korean_Wansung_CI_AI NULL,
	STEP_CD varchar(2) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	INS_YMDHMS datetime NOT NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL
);
 CREATE NONCLUSTERED INDEX IX_SESSION_EMP_EMPID ON dbo.SESSION_EMP (  EVU_EMP_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_SESSION_EMP_SESSIONNM ON dbo.SESSION_EMP (  SESSION_NM ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_SESSION_EMP_STDID ON dbo.SESSION_EMP (  EVU_STD_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_SESSION_EMP_STEPCD ON dbo.SESSION_EMP (  STEP_CD ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
	
CREATE TABLE wondermom89_mj89ya.dbo.[USER] (
	EMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EMP_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	ENTER_TYPE varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	ENTER_YMD varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	EMP_TYPE varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	OFFICE_TEL_NO varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	TEL_NO varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	EGC_TEL_NO varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	MOBILE_NO varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	PHOTO_YN char(1) COLLATE Korean_Wansung_CI_AI NULL,
	PHOTO_PATH varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	STA_YMD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	END_YMD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	SEQ_NO int NULL,
	STAT_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	BIZPL_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	ORG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	ORG_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	ORG_ID2 varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	ORG_NM2 varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	EMP_GRADE_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EMP_GRADE_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	DUTY_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	DUTY_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	JG_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	JG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	JOB_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	JOB_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	JOB_ID2 varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	JOB_NM2 varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	POST_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	POST_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	BAND_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	GRADE_STA_YMD date NULL,
	POST_AGE int DEFAULT 0 NULL,
	GRP_YMD varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	BIRTH_YMD varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS date NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS date NULL,
	UPT_YMDHMS datetime NULL,
	CONSTRAINT PK_USER PRIMARY KEY (EMP_ID)
);

CREATE TABLE wondermom89_mj89ya.dbo.USER_BATCH (
	EMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	EMP_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	ENTER_TYPE varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	ENTER_YMD varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	EMP_TYPE varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	OFFICE_TEL_NO varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	TEL_NO varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	EGC_TEL_NO varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	MOBILE_NO varchar(50) COLLATE Korean_Wansung_CI_AI NULL,
	PHOTO_YN char(1) COLLATE Korean_Wansung_CI_AI NULL,
	PHOTO_PATH varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	STA_YMD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	END_YMD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	SEQ_NO int NULL,
	STAT_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	BIZPL_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	ORG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	ORG_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	ORG_ID2 varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	ORG_NM2 varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	EMP_GRADE_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	EMP_GRADE_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	DUTY_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	DUTY_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	JG_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	JG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	JOB_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	JOB_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	JOB_ID2 varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	JOB_NM2 varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	POST_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	POST_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	BAND_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	GRP_YMD varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	GRADE_STA_YMD date NULL,
	POST_AGE int NULL,
	BIRTH_YMD varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS date NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS date NULL,
	UPT_YMDHMS datetime NULL,
	CONSTRAINT PK_USER_BATCH PRIMARY KEY (EMP_ID)
);


CREATE TABLE wondermom89_mj89ya.dbo.USER_CAREER (
	EMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	STA_YMD varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	END_YMD varchar(8) COLLATE Korean_Wansung_CI_AI NULL,
	APPNT_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	APPNT_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	ORG_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	ORG_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	POST_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	POST_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	UPT_YMDHMS datetime NULL
);


CREATE TABLE wondermom89_mj89ya.dbo.USER_SCHL (
	EMP_ID varchar(20) COLLATE Korean_Wansung_CI_AI NOT NULL,
	SEQ_NO int NOT NULL,
	STA_YM varchar(6) COLLATE Korean_Wansung_CI_AI NULL,
	END_YM varchar(6) COLLATE Korean_Wansung_CI_AI NULL,
	DEGREE_NO varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	SCHO_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	GRD_SCHL_TYPE varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	SCHL_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	SCHL_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	MAJOR_GRP_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MAJOR_GRP_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	MAJOR_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MAJOR_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	MAJOR2_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MAJOR2_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	MINOR_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MINOR_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	DEGREE_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	GRADU_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	PNB_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	DAY_NIGHT_CD varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	TRANS_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	PLACE_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	LAST_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	AFT_YN char(1) COLLATE Korean_Wansung_CI_AI DEFAULT 'N' NOT NULL,
	THESIS_NM varchar(100) COLLATE Korean_Wansung_CI_AI NULL,
	INS_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	INS_YMDHMS datetime NULL,
	MOD_USER_ID varchar(20) COLLATE Korean_Wansung_CI_AI NULL,
	MOD_YMDHMS datetime NULL,
	UPT_YMDHMS datetime NULL,
	COM_YN varchar(1) COLLATE Korean_Wansung_CI_AI NOT NULL,
	CONSTRAINT PK_USER_SCHL PRIMARY KEY (EMP_ID,SEQ_NO)
);



--With Tree_Org(OBJ_ID, OBJ_NM, depth, SEQ_NO, PAR_OBJ_ID, PAR_OBJ_NM, RCV_OBJ_ID, PAR_OBJ_ID1, PAR_OBJ_ID2, PAR_OBJ_ID3, PAR_OBJ_ID4, PAR_OBJ_NM1, PAR_OBJ_NM2, PAR_OBJ_NM3, PAR_OBJ_NM4)
With  Tree_Org(OBJ_ID, OBJ_NM, depth, SEQ_NO, PAR_OBJ_ID,PAR_OBJ_NM)
As
(
 Select  
	OBJ_ID, 
	OBJ_NM,
	1 As depth, 
	CAST(REPLACE(STR(ISNULL(SEQ_NO,'0'), 4),' ','0') as varchar(20)) SEQ_NO, 
	PAR_OBJ_ID,
	CAST('' as varchar(100)) AS PAR_OBJ_NM
--	CAST(OBJ_ID as varchar(200)) AS RCV_OBJ_ID,
--	CAST('' as varchar(20)) AS PAR_OBJ_ID1, 
--	CAST('' as varchar(20)) AS PAR_OBJ_ID2, 
--	CAST('' as varchar(20)) AS PAR_OBJ_ID3, 
--	CAST('' as varchar(20)) AS PAR_OBJ_ID4,
--	CAST('' as varchar(100)) AS PAR_OBJ_NM1, 
--	CAST('' as varchar(100)) AS PAR_OBJ_NM2, 
--	CAST('' as varchar(100)) AS PAR_OBJ_NM3, 
--	CAST('' as varchar(100)) AS PAR_OBJ_NM4
 From   COMM_ORG
 Where  PAR_OBJ_ID = '0000000000' 
 Union All
 Select  
	A.OBJ_ID, 
	A.OBJ_NM, 
	depth + 1 As depth,  
	CAST(B.SEQ_NO + CAST(REPLACE(STR(ISNULL(A.SEQ_NO,'0'), 4),' ','0') as varchar(4))  as  varchar(20)) SEQ_NO, 
	A.PAR_OBJ_ID, 
	A.OBJ_NM AS PAR_OBJ_NM  
--	CAST(RCV_OBJ_ID+'|'+A.OBJ_ID as varchar(200))  AS RCV_OBJ_ID,
--	(CASE WHEN depth=1 THEN B.OBJ_ID ELSE  PAR_OBJ_ID1 END) AS PAR_OBJ_ID1,
--	(CASE WHEN depth=2 THEN B.OBJ_ID ELSE  PAR_OBJ_ID2 END) AS PAR_OBJ_ID2,
--	(CASE WHEN depth=3 THEN B.OBJ_ID ELSE  PAR_OBJ_ID3 END) AS PAR_OBJ_ID3,
--	(CASE WHEN depth=4 THEN B.OBJ_ID ELSE  PAR_OBJ_ID4 END) AS PAR_OBJ_ID4,
--	(CASE WHEN depth=1 THEN B.OBJ_NM ELSE  PAR_OBJ_NM1 END) AS PAR_OBJ_NM1,
--	(CASE WHEN depth=2 THEN B.OBJ_NM ELSE  PAR_OBJ_NM2 END) AS PAR_OBJ_NM2,
--	(CASE WHEN depth=3 THEN B.OBJ_NM ELSE  PAR_OBJ_NM3 END) AS PAR_OBJ_NM3,
--	(CASE WHEN depth=4 THEN B.OBJ_NM ELSE  PAR_OBJ_NM4 END) AS PAR_OBJ_NM4
 From   COMM_ORG A
 Inner Join Tree_Org  B On A.PAR_OBJ_ID = B.OBJ_ID
)
Select 
	OBJ_ID, 
	OBJ_NM, 
	depth, 
	SEQ_NO,
	PAR_OBJ_ID, 
	PAR_OBJ_NM 
--	RCV_OBJ_ID, 
--	PAR_OBJ_ID1, 
--	PAR_OBJ_ID2, 
--	PAR_OBJ_ID3, 
--	PAR_OBJ_ID4,
--	PAR_OBJ_NM1,
--	PAR_OBJ_NM2,
--	PAR_OBJ_NM3,
--	PAR_OBJ_NM4
From  Tree_Org;




-------------- create view
-- dbo.COMM_ORG_VIEW source
--CREATE VIEW [dbo].[COMM_ORG_VIEW] AS
With Tree_Org(OBJ_ID, OBJ_NM, depth, SEQ_NO, PAR_OBJ_ID, PAR_OBJ_NM, RCV_OBJ_ID, PAR_OBJ_ID1, PAR_OBJ_ID2, PAR_OBJ_ID3, PAR_OBJ_ID4, PAR_OBJ_NM1, PAR_OBJ_NM2, PAR_OBJ_NM3, PAR_OBJ_NM4)
As
(
 Select  
	OBJ_ID, 
	OBJ_NM,
	1 As depth, 
	CAST(REPLACE(STR(ISNULL(SEQ_NO,'0'), 4),' ','0') as varchar(20)) SEQ_NO, 
	PAR_OBJ_ID, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM,
	CAST(OBJ_ID as varchar(200)) AS RCV_OBJ_ID,
	CAST('-' as varchar(20)) AS PAR_OBJ_ID1, 
	CAST('-' as varchar(20)) AS PAR_OBJ_ID2, 
	CAST('-' as varchar(20)) AS PAR_OBJ_ID3, 
	CAST('-' as varchar(20)) AS PAR_OBJ_ID4,
	CAST('-' as varchar(100)) AS PAR_OBJ_NM1, 
	CAST('-' as varchar(100)) AS PAR_OBJ_NM2, 
	CAST('-' as varchar(100)) AS PAR_OBJ_NM3, 
	CAST('-' as varchar(100)) AS PAR_OBJ_NM4
 From   COMM_ORG
 Where  PAR_OBJ_ID = '0000000000' 
 Union All
 Select  
	A.OBJ_ID, 
	A.OBJ_NM, 
	depth + 1 As depth,  
	CAST(B.SEQ_NO + CAST(REPLACE(STR(ISNULL(A.SEQ_NO,'0'), 4),' ','0') as varchar(4))  as  varchar(20)) SEQ_NO, 
	A.PAR_OBJ_ID, 
	B.PAR_OBJ_NM AS PAR_OBJ_NM,
	CAST(RCV_OBJ_ID+'|'+A.OBJ_ID as varchar(200))  AS RCV_OBJ_ID,
	(CASE WHEN depth=1 THEN B.OBJ_ID ELSE  PAR_OBJ_ID1 END) AS PAR_OBJ_ID1,
	(CASE WHEN depth=2 THEN B.OBJ_ID ELSE  PAR_OBJ_ID2 END) AS PAR_OBJ_ID2,
	(CASE WHEN depth=3 THEN B.OBJ_ID ELSE  PAR_OBJ_ID3 END) AS PAR_OBJ_ID3,
	(CASE WHEN depth=4 THEN B.OBJ_ID ELSE  PAR_OBJ_ID4 END) AS PAR_OBJ_ID4,
	(CASE WHEN depth=1 THEN B.OBJ_NM ELSE  PAR_OBJ_NM1 END) AS PAR_OBJ_NM1,
	(CASE WHEN depth=2 THEN B.OBJ_NM ELSE  PAR_OBJ_NM2 END) AS PAR_OBJ_NM2,
	(CASE WHEN depth=3 THEN B.OBJ_NM ELSE  PAR_OBJ_NM3 END) AS PAR_OBJ_NM3,
	(CASE WHEN depth=4 THEN B.OBJ_NM ELSE  PAR_OBJ_NM4 END) AS PAR_OBJ_NM4
 From   COMM_ORG A
 Inner Join Tree_Org  B On A.PAR_OBJ_ID = B.OBJ_ID
)
Select 
	OBJ_ID, OBJ_NM, depth, SEQ_NO, 
	PAR_OBJ_ID, PAR_OBJ_NM, 
	RCV_OBJ_ID, 
	PAR_OBJ_ID1, 
	PAR_OBJ_ID2, 
	PAR_OBJ_ID3, 
	PAR_OBJ_ID4,
	PAR_OBJ_NM1,
	PAR_OBJ_NM2,
	PAR_OBJ_NM3,
	PAR_OBJ_NM4
From  Tree_Org;



----- create view with절
With Tree_Org(OBJ_ID, OBJ_NM, depth, SEQ_NO, PAR_OBJ_ID, PAR_OBJ_NM, RCV_OBJ_ID, PAR_OBJ_ID1, PAR_OBJ_ID2, PAR_OBJ_ID3, PAR_OBJ_ID4, PAR_OBJ_NM1, PAR_OBJ_NM2, PAR_OBJ_NM3, PAR_OBJ_NM4)
As
(
 Select  
	OBJ_ID, 
	OBJ_NM,
	1 As depth, 
	CAST(REPLACE(STR(ISNULL(SEQ_NO,'0'), 4),' ','0') as varchar(20)) SEQ_NO, 
	PAR_OBJ_ID, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM,
	CAST(OBJ_ID as varchar(200)) AS RCV_OBJ_ID,
	CAST('' as varchar(20)) AS PAR_OBJ_ID1, 
	CAST('' as varchar(20)) AS PAR_OBJ_ID2, 
	CAST('' as varchar(20)) AS PAR_OBJ_ID3, 
	CAST('' as varchar(20)) AS PAR_OBJ_ID4,
	CAST('' as varchar(100)) AS PAR_OBJ_NM1, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM2, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM3, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM4
 From   COMM_ORG
 Where  PAR_OBJ_ID = '0000000000' 
 Union All
 Select  
	A.OBJ_ID, 
	A.OBJ_NM, 
	depth + 1 As depth,  
	CAST(B.SEQ_NO + CAST(REPLACE(STR(ISNULL(A.SEQ_NO,'0'), 4),' ','0') as varchar(4))  as  varchar(20)) SEQ_NO, 
	A.PAR_OBJ_ID, 
	B.OBJ_NM AS PAR_OBJ_NM,
	CAST(RCV_OBJ_ID+'|'+A.OBJ_ID as varchar(200))  AS RCV_OBJ_ID,
	(CASE WHEN depth=1 THEN B.OBJ_ID ELSE  PAR_OBJ_ID1 END) AS PAR_OBJ_ID1,
	(CASE WHEN depth=2 THEN B.OBJ_ID ELSE  PAR_OBJ_ID2 END) AS PAR_OBJ_ID2,
	(CASE WHEN depth=3 THEN B.OBJ_ID ELSE  PAR_OBJ_ID3 END) AS PAR_OBJ_ID3,
	(CASE WHEN depth=4 THEN B.OBJ_ID ELSE  PAR_OBJ_ID4 END) AS PAR_OBJ_ID4,
	(CASE WHEN depth=1 THEN B.OBJ_NM ELSE  PAR_OBJ_NM1 END) AS PAR_OBJ_NM1,
	(CASE WHEN depth=2 THEN B.OBJ_NM ELSE  PAR_OBJ_NM2 END) AS PAR_OBJ_NM2,
	(CASE WHEN depth=3 THEN B.OBJ_NM ELSE  PAR_OBJ_NM3 END) AS PAR_OBJ_NM3,
	(CASE WHEN depth=4 THEN B.OBJ_NM ELSE  PAR_OBJ_NM4 END) AS PAR_OBJ_NM4
 From   COMM_ORG A
 Inner Join Tree_Org  B On A.PAR_OBJ_ID = B.OBJ_ID
)
Select 
	OBJ_ID, OBJ_NM, depth, SEQ_NO, 
	PAR_OBJ_ID, PAR_OBJ_NM, 
	RCV_OBJ_ID, 
	PAR_OBJ_ID1, 
	PAR_OBJ_ID2, 
	PAR_OBJ_ID3, 
	PAR_OBJ_ID4,
	PAR_OBJ_NM1,
	PAR_OBJ_NM2,
	PAR_OBJ_NM3,
	PAR_OBJ_NM4
From  Tree_Org;

--------
 Select  
	OBJ_ID, 
	OBJ_NM,
	1 As depth, 
	CAST(REPLACE(STR(ISNULL(SEQ_NO,'0'), 4),' ','0') as varchar(20)) SEQ_NO, 
	PAR_OBJ_ID, 
	CAST(OBJ_NM as varchar(100)) AS PAR_OBJ_NM,
	CAST(OBJ_ID as varchar(200)) AS RCV_OBJ_ID,
	CAST(' ' as varchar(20)) AS PAR_OBJ_ID1, 
	CAST(PAR_OBJ_ID as varchar(20)) AS PAR_OBJ_ID2, 
	CAST(PAR_OBJ_ID as varchar(20)) AS PAR_OBJ_ID3, 
	CAST(PAR_OBJ_ID as varchar(20)) AS PAR_OBJ_ID4,
	CAST('' as varchar(100)) AS PAR_OBJ_NM1, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM2, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM3, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM4
 From   COMM_ORG
 Where  PAR_OBJ_ID = '0000000000'; 

select * 
from COMM_ORG co
where co.PAR_OBJ_ID= '0000000000';

with Test (OBJ_ID,OBJ_NM,depth,SEQ_NO,PAR_OBJ_ID,PAR_OBJ_NM,RCV_OBJ_ID,PAR_OBJ_ID1,PAR_OBJ_ID2,PAR_OBJ_ID3,PAR_OBJ_ID4,PAR_OBJ_NM1,PAR_OBJ_NM2,PAR_OBJ_NM3,PAR_OBJ_NM4)
AS ( 
Select  
	OBJ_ID, 
	OBJ_NM,
	1 As depth, 
	CAST(REPLACE(STR(ISNULL(SEQ_NO,'0'), 4),' ','0') as varchar(20)) SEQ_NO, 
	PAR_OBJ_ID, 
	CAST(OBJ_NM as varchar(100)) AS PAR_OBJ_NM,
	CAST(OBJ_ID as varchar(200)) AS RCV_OBJ_ID,
	CAST(' ' as varchar(20)) AS PAR_OBJ_ID1, 
	CAST('' as varchar(20)) AS PAR_OBJ_ID2, 
	CAST('' as varchar(20)) AS PAR_OBJ_ID3, 
	CAST('' as varchar(20)) AS PAR_OBJ_ID4,
	CAST('' as varchar(100)) AS PAR_OBJ_NM1, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM2, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM3, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM4
 From   COMM_ORG
 Where  PAR_OBJ_ID = '0000000000'
 union 
  Select  
	OBJ_ID, 
	OBJ_NM,
	1 As depth, 
	CAST(REPLACE(STR(ISNULL(SEQ_NO,'0'), 4),' ','0') as varchar(20)) SEQ_NO, 
	PAR_OBJ_ID, 
	CAST(OBJ_NM as varchar(100)) AS PAR_OBJ_NM,
	CAST(OBJ_ID as varchar(200)) AS RCV_OBJ_ID,
	CAST(' ' as varchar(20)) AS PAR_OBJ_ID1, 
	CAST(PAR_OBJ_ID as varchar(20)) AS PAR_OBJ_ID2, 
	CAST(PAR_OBJ_ID as varchar(20)) AS PAR_OBJ_ID3, 
	CAST(PAR_OBJ_ID as varchar(20)) AS PAR_OBJ_ID4,
	CAST('' as varchar(100)) AS PAR_OBJ_NM1, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM2, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM3, 
	CAST('' as varchar(100)) AS PAR_OBJ_NM4
 From   COMM_ORG
 Where  PAR_OBJ_ID = '0000000000')
select * from Test;


