SELECT * 
		FROM EVU_STD
		WHERE OPEN_YN ='Y'
		ORDER BY  EVU_YY DESC, EVU_STD_ID DESC

SELECT 
			D.EVU_STD_ID, D.EVU_STD_NM, 
			S.EVU_STEP_CD, S.EVU_STEP_NM, S.EVU_SDATE, S.EVU_EDATE, S.ORDER_NO
		FROM EVU_STEP S INNER JOIN EVU_STD D ON (S.EVU_STD_ID = D.EVU_STD_ID)
		WHERE S.EVU_STEP_CD LIKE '%1' AND D.OPEN_YN = 'Y'
		ORDER BY D.EVU_YY DESC,D.EVU_STD_ID DESC, S.EVU_STEP_CD DESC

 SELECT 
			S.EVU_STD_ID, S.EVU_STD_NM, SP.EVU_STEP_CD, SP.EVU_STEP_NM, 
			ST.EVU_STAT_SEQ, ST.CHASU, ST.EVU_STAT_CD, ST.EVU_STAT_NM
		FROM EVU_STD S INNER JOIN EVU_STEP SP ON (S.EVU_STD_ID = SP.EVU_STD_ID) 
			INNER JOIN EVU_STAT ST ON (SP.EVU_STEP_CD = ST.EVU_STEP_CD)
		WHERE S.EVU_STD_ID = '202201'


 SELECT * FROM COMM_ORG_VIEW
		WHERE 1=1

		ORDER BY SEQ_NO


 SELECT * 
		FROM COMM_GRADE 
		WHERE IDX_CD = '/SY04'
		AND USE_YN = 'Y'
		ORDER BY DP_ORDER;


 SELECT * 
		FROM COMM_GRADE 
		WHERE IDX_CD = '/SY05'
		AND USE_YN = 'Y'
		ORDER BY DP_ORDER;


 SELECT COUNT(*) FROM(
		SELECT	
			Y1.ADMIN_PER_SEQ,
			Y1.EVU_EMP_ID,
			Y1.EVU_EMP_NO, 
			U.EMP_NM,
			Y1.SCORE,
			Y1.RANK,
			Y1.RESULT_TYPE,
			Y1.Y18_PGRD,Y1.Y18_CGRD,Y1.Y17_PGRD,Y1.Y17_CGRD,Y1.Y17_OGRD,Y1.EVU_YY,Y1.RE_YN,
			LEFT(U.BIRTH_YMD,4) BIRTH_YMD,
			U.DUTY_NM,
			C.SEQ_NO,
			U.POST_CD, U.POST_NM, U.POST_AGE,
			U.JOB_ID,U.JOB_NM,
			U.POST_AGE GRADE_STA_YEAR,
			C.OBJ_ID, C.PAR_OBJ_ID1, C.PAR_OBJ_ID2, C.PAR_OBJ_ID3, C.PAR_OBJ_ID4, C.OBJ_NM, C.PAR_OBJ_NM2 PAR_OBJ_NM2,
			ISNULL(TP1.TOT_CFM_GRD_4Q, '') Y1_PGRD,  
			ISNULL(TC1.TOT_CFM_GRD_4Q, '') Y1_CGRD, 
			ISNULL(TP2.TOT_CFM_GRD_4Q, '') Y2_PGRD,
			ISNULL(TC2.TOT_CFM_GRD_4Q, '') Y2_CGRD,
			ISNULL(TP3.TOT_CFM_GRD_4Q, '') Y3_PGRD,  
			ISNULL(TC3.TOT_CFM_GRD_4Q, '') Y3_CGRD,
			C.PAR_OBJ_NM CHARGE_ORG,
			U.ORG_NM GR_NM,
			MU1.EMP_NM MNG_NM
		FROM 
			(SELECT ADMIN_PER_SEQ, EVU_EMP_NO, EVU_EMP_ID,EVU_MNG_ID,SCORE,RANK,RESULT_TYPE,Y18_PGRD,Y18_CGRD,Y17_PGRD,Y17_CGRD,Y17_OGRD,EVU_YY,RE_YN, E.EVU_STAT_CD FROM (
			SELECT B.ADMIN_PER_SEQ,A.EVU_EMP_ID,A.EVU_STD_ID,A.EVU_MNG_ID,B.SCORE,B.RANK,B.RESULT_TYPE,E.EVU_EMP_NO,B.Y18_PGRD,B.Y18_CGRD,B.Y17_PGRD,B.Y17_CGRD,B.Y17_OGRD,B.RE_YN , E.EVU_STAT_CD
			FROM  ADMIN_PER_AUTH A
			LEFT JOIN  ADMIN_PER B ON(A.EVU_EMP_ID = B.EVU_EMP_ID AND A.EVU_STD_ID = B.EVU_STD_ID AND A.EVU_STD_ID = '202201' )
			LEFT JOIN EVU_EMP E ON(A.EVU_EMP_ID = E.EVU_EMP_ID AND A.EVU_STD_ID = E.EVU_STD_ID) 
			)E JOIN EVU_STD K ON(E.EVU_STD_ID = K.EVU_STD_ID) WHERE K.EVU_YY = '2022' ) Y1
			INNER JOIN [USER] U ON (Y1.EVU_EMP_ID = U.EMP_ID)
			LEFT JOIN EVU_TOT TP1 ON (Y1.EVU_EMP_NO = TP1.EVU_EMP_NO AND TP1.EVU_TYPE = 'P') 
			LEFT JOIN EVU_TOT TC1 ON (Y1.EVU_EMP_NO = TC1.EVU_EMP_NO AND TC1.EVU_TYPE = 'C') 
			LEFT JOIN (SELECT EVU_EMP_NO, EVU_EMP_ID FROM EVU_EMP E JOIN EVU_STD K ON(E.EVU_STD_ID = K.EVU_STD_ID) WHERE K.EVU_YY = '2021' ) Y2 ON (Y1.EVU_EMP_ID = Y2.EVU_EMP_ID)
			LEFT JOIN EVU_TOT TP2 ON (Y2.EVU_EMP_NO = TP2.EVU_EMP_NO AND TP2.EVU_TYPE = 'P')
			LEFT JOIN EVU_TOT TC2 ON (Y2.EVU_EMP_NO = TC2.EVU_EMP_NO AND TC2.EVU_TYPE = 'C')
			LEFT JOIN (SELECT E.EVU_EMP_NO, E.EVU_EMP_ID, K.EVU_YY FROM EVU_EMP E JOIN EVU_STD K ON(E.EVU_STD_ID = K.EVU_STD_ID) WHERE K.EVU_YY = '2020') Y3 ON (Y1.EVU_EMP_ID = Y3.EVU_EMP_ID)
			LEFT JOIN EVU_TOT TP3 ON (Y3.EVU_EMP_NO = TP3.EVU_EMP_NO AND TP3.EVU_TYPE = 'P')
			LEFT JOIN EVU_TOT TC3 ON (Y3.EVU_EMP_NO = TC3.EVU_EMP_NO AND TC3.EVU_TYPE = 'C')
			LEFT JOIN COMM_ORG_VIEW C ON (C.OBJ_ID = U.ORG_ID)
			LEFT JOIN [USER] MU1 ON  (Y1.EVU_MNG_ID = MU1.EMP_ID) 

		WHERE 1=1 

	    )T
	    WHERE 1= 1

