
SELECT E.EVU_EMP_NO, E.EVU_EMP_ID, U.EMP_NM, U.JOB_NM, U.DUTY_NM, U.DUTY_CD, U.POST_CD, U.POST_NM, C.PAR_OBJ_ID ORG_ID, C.PAR_OBJ_NM ORG_NM, 
			U.ORG_ID PAR_ORG_ID, U.ORG_NM PAR_ORG_NM, U.POST_AGE GRADE_STA_YEAR, C.PAR_OBJ_NM2 PAR_OBJ_NM2,
			ST.EVU_STAT_NM, SP.EVU_STEP_NM, MOVE_PERIOD_CD,
			TP.SELF_GRD_1Q PSELF_GRD_1Q, TP.MNG1_GRD_1Q PMNG1_GRD_1Q, TP.MNG2_GRD_1Q PMNG2_GRD_1Q, TP.TOT_GRD_1Q PTOT_GRD_1Q, TP.TOT_CFM_GRD_1Q PTOT_CFM_GRD_1Q,
			TP.SELF_GRD_2Q PSELF_GRD_2Q, TP.MNG1_GRD_2Q PMNG1_GRD_2Q, TP.MNG2_GRD_2Q PMNG2_GRD_2Q, TP.TOT_GRD_2Q PTOT_GRD_2Q, TP.TOT_CFM_GRD_2Q PTOT_CFM_GRD_2Q,
			TP.SELF_GRD_3Q PSELF_GRD_3Q, TP.MNG1_GRD_3Q PMNG1_GRD_3Q, TP.MNG2_GRD_3Q PMNG2_GRD_3Q, TP.TOT_GRD_3Q PTOT_GRD_3Q, TP.TOT_CFM_GRD_3Q PTOT_CFM_GRD_3Q,
			TP.SELF_GRD_4Q PSELF_GRD_4Q, TP.MNG1_GRD_4Q PMNG1_GRD_4Q, TP.MNG2_GRD_4Q PMNG2_GRD_4Q, TP.TOT_GRD_4Q PTOT_GRD_4Q, TP.TOT_CFM_GRD_4Q PTOT_CFM_GRD_4Q,
			TC.SELF_GRD_1Q CSELF_GRD_1Q, TC.MNG1_GRD_1Q CMNG1_GRD_1Q, TC.MNG2_GRD_1Q CMNG2_GRD_1Q, TP.TOT_GRD_1Q CTOT_GRD_1Q, TC.TOT_CFM_GRD_1Q CTOT_CFM_GRD_1Q,
			TC.SELF_GRD_2Q CSELF_GRD_2Q, TC.MNG1_GRD_2Q CMNG1_GRD_2Q, TC.MNG2_GRD_2Q CMNG2_GRD_2Q, TP.TOT_GRD_2Q CTOT_GRD_2Q, TC.TOT_CFM_GRD_2Q CTOT_CFM_GRD_2Q,
			TC.SELF_GRD_3Q CSELF_GRD_3Q, TC.MNG1_GRD_3Q CMNG1_GRD_3Q, TC.MNG2_GRD_3Q CMNG2_GRD_3Q, TP.TOT_GRD_3Q CTOT_GRD_3Q, TC.TOT_CFM_GRD_3Q CTOT_CFM_GRD_3Q,
			TC.SELF_GRD_4Q CSELF_GRD_4Q, TC.MNG1_GRD_4Q CMNG1_GRD_4Q, TC.MNG2_GRD_4Q CMNG2_GRD_4Q, TP.TOT_GRD_4Q CTOT_GRD_4Q, TC.TOT_CFM_GRD_4Q CTOT_CFM_GRD_4Q
			,CASE WHEN  U.JOB_NM  = 'PL' OR  U.JOB_NM ='지사장' OR  U.JOB_NM = '연구소장' THEN 1
			 WHEN  U.JOB_NM  = 'Manager' THEN 2
			 ELSE 2 
			 END AS JOB_ORDER
		FROM EVU_EMP E INNER JOIN [USER] U ON (E.EVU_EMP_ID = U.EMP_ID)
			INNER JOIN EVU_STD S ON (E.EVU_STD_ID = S.EVU_STD_ID)
			LEFT JOIN EVU_MNG M1 ON (E.EVU_EMP_NO = M1.EVU_EMP_NO AND M1.chasu = 1)
			LEFT JOIN [USER] MU1 ON (M1.EVU_MNG_ID = MU1.EMP_ID)
			LEFT JOIN EVU_MNG M2 ON (E.EVU_EMP_NO = M2.EVU_EMP_NO AND M2.chasu = 2)
			LEFT JOIN [USER] MU2 ON (M2.EVU_MNG_ID = MU2.EMP_ID)
			LEFT JOIN EVU_MNG M3 ON (E.EVU_EMP_NO = M3.EVU_EMP_NO AND M3.chasu = 3)
			LEFT JOIN [USER] MU3 ON (M3.EVU_MNG_ID = MU3.EMP_ID)
			LEFT JOIN EVU_STAT ST ON (E.CHASU = ST.CHASU AND E.CUR_STEP_CD = ST.EVU_STEP_CD AND E.EVU_STAT_CD = ST.EVU_STAT_CD)
			LEFT JOIN EVU_STEP SP ON (ST.EVU_STEP_CD = SP.EVU_STEP_CD AND SP.EVU_STD_ID = S.EVU_STD_ID)
			LEFT JOIN COMM_ORG_VIEW C ON (U.ORG_ID = C.OBJ_ID)
			LEFT JOIN EVU_TOT TP ON (E.EVU_EMP_NO = TP.EVU_EMP_NO AND TP.EVU_TYPE = 'P')
			LEFT JOIN EVU_TOT TC ON (E.EVU_EMP_NO = TC.EVU_EMP_NO AND TC.EVU_TYPE = 'C')
			WHERE E.EVU_STD_ID = '202201'

	    	ORDER BY C.SEQ_NO, JOB_ORDER ASC, U.POST_CD DESC,  U.POST_AGE DESC, U.EMP_NM ASC
